services:

  # PostgreSQL Containers (PostGIS + pgadmin)
  postgres:
    image: postgis/postgis:18-3.6
    container_name: "${COMPOSE_PROJECT_NAME:-dc}-postgres"
    restart: always
    ports:
      - "${PORT_POSTGRES:-25432}:5432"
    profiles:
      - db
      - dbui
      - ontop
      - frontend
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/:z
      - postgres-data:/var/lib/postgresql:z
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "${USERID:-user}"
      POSTGRES_PASSWORD: "${USERPWD:-user}"
    command: ["postgres"]
    stop_grace_period: 5m
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${USERID:-user}", "-d", "db"]
      interval: 10s
      timeout: 10s
      retries: 15

  pgadmin:
    image: dpage/pgadmin4:9.18
    container_name: "${COMPOSE_PROJECT_NAME:-dc}-pgadmin"
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - dbui
    ports:
      - "${PORT_PGADMIN:-20080}:80"
    volumes:
      - ./scripts/pgadmin4/servers.json:/pgadmin4/servers.json:z
      - pgadmin-data:/var/lib/pgadmin:z
    environment:
      PGADMIN_DEFAULT_EMAIL: ${USEREMAIL:-user@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${USERPWD:-user}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_DISABLE_POSTFIX: "true"
      GUNICORN_ACCESS_LOGFILE: "/dev/null"

  # Ontop
  ontop:
    image: ontop/ontop
    container_name: "${COMPOSE_PROJECT_NAME:-dc}-ontop"
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/ontology.ttl
      ONTOP_MAPPING_FILE: /opt/ontop/input/ontology.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/ontology.properties
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_DEV_MODE: "true"
      ONTOP_LAZY_INIT: "true"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - ontop
      - frontend
    volumes:
      - ./ontology/:/opt/ontop/input/:z
      - ./scripts/jdbc/:/opt/ontop/jdbc/:z
    ports:
      - "${PORT_ONTOP:-8887}:8080"
    healthcheck:
      test: ["CMD", "wget", "localhost:8080", "-O", "/tmp/index.html"]
      interval: 10s
      timeout: 10s
      retries: 15

  # The static HTTP service
  frontend:
    build: app
    image: "${COMPOSE_PROJECT_NAME:-dc}-frontend:latest"
    container_name: "${COMPOSE_PROJECT_NAME:-dc}-frontend"
    restart: always
    depends_on:
      ontop:
        condition: service_healthy
    profiles:
      - frontend
    ports:
      - "${PORT_FRONTEND:-8888}:${PORT_FRONTEND:-8888}"
    command: [ "python", "/app/serve.py" ]
    environment:
      PORT: ${PORT_FRONTEND:-8888}
    healthcheck:
      test: [
        "CMD", "python", "-c",
        "import urllib.request; urllib.request.urlopen('http://localhost:${PORT_FRONTEND:-8888}').read()"
      ]
      interval: 10s
      timeout: 10s
      retries: 15

volumes:
  postgres-data:
  pgadmin-data:
